GET http://localhost:3000/songs


### pagination
GET http://localhost:3000/songs/paginate/

### create new song
POST  http://localhost:3000/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VySWQiOjMsImFydGlzdElkIjoxLCJpYXQiOjE3MTQ5OTU2NzYsImV4cCI6MTcxNTA4MjA3Nn0.iliMqChv90V92L9NDbYTX5UHMjQYOfE4EQz-a_o8cFY

{
  "title": "Song 2",
  "artists": [1,2],
  "lyrics": "Lyrics 1",
  "duration": "02:30",
  "releaseDate": "2019-01-01"
}

### fetch one song
GET http://localhost:3000/songs/5/


### delete song
DELETE http://localhost:3000/songs/1/

### update song
PUT http://localhost:3000/songs/2/
Content-Type: application/json

{
  "title": "Song 3333",
  "lyrics": "Lyrics 1",
  "duration": "02:30",
  "relaeaseDate": "2019-01-01"
}
### create new playlist
POST  http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "Playlist 1",
  "songs": [6],
  "user": 1
}

### create new user
POST  http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "test@test.com",
  "password": "123456"
}

### create new user
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "test@test.com",
  "password": "123456"
}

### login
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456"
}

### profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VySWQiOjMsImFydGlzdElkIjoxLCJpYXQiOjE3MTQ5OTU2NzYsImV4cCI6MTcxNTA4MjA3Nn0.iliMqChv90V92L9NDbYTX5UHMjQYOfE4EQz-a_o8cFY


### Enable 2FA
Get http://localhost:3000/auth/enable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VySWQiOjMsImFydGlzdElkIjoxLCJpYXQiOjE3MTU1MTU3MzksImV4cCI6MTcxNTYwMjEzOX0.GKLzJGCZNorPOjfXMjUl7m_W5W08ndjlXPJPsMamIgo

### Validate 2FA
Post http://localhost:3000/auth/verify-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VySWQiOjMsImFydGlzdElkIjoxLCJpYXQiOjE3MTU1MTU3MzksImV4cCI6MTcxNTYwMjEzOX0.GKLzJGCZNorPOjfXMjUl7m_W5W08ndjlXPJPsMamIgo
Content-Type: application/json

{
  "token": "991856"
}

### Disable 2FA
Get http://localhost:3000/auth/disable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VySWQiOjMsImFydGlzdElkIjoxLCJpYXQiOjE3MTU1MTIxNTMsImV4cCI6MTcxNTU5ODU1M30.5XmCr21AxmWmX_ByEMjs4RELLXFrm14sGPExozbQxIs