GET http://localhost:3000/songs


### pagination
GET http://localhost:3000/songs/paginate/

### create new song
POST  http://localhost:3000/songs
Content-Type: application/json

{
  "title": "Song 2",
  "artists": [1,2],
  "lyrics": "Lyrics 1",
  "duration": "02:30",
  "releaseDate": "2019-01-01"
}

### fetch one song
GET http://localhost:3000/songs/5/


### delete song
DELETE http://localhost:3000/songs/1/

### update song
PUT http://localhost:3000/songs/2/
Content-Type: application/json

{
  "title": "Song 3333",
  "lyrics": "Lyrics 1",
  "duration": "02:30",
  "relaeaseDate": "2019-01-01"
}
### create new playlist
POST  http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "Playlist 1",
  "songs": [6],
  "user": 1
}

### create new user
POST  http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "test@test.com",
  "password": "123456"
}

### create new user
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "test@test.com",
  "password": "123456"
}

### login
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456"
}

### profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VySWQiOjMsImlhdCI6MTcxNDk5MDYzNCwiZXhwIjoxNzE1MDc3MDM0fQ.ks0LEXOMwelCEj1cJjY31Y5qAclP_irl7eWZlRKwvqc